### ISSUE TITLE
Use YAML instead of embedded JSON in acceptance test data

### ISSUE THREAD

**Issue by aslakhellesoy** [cucumber/cucumber-expressions#33]
**Is your feature request related to a problem? Please describe.**

The various `testdata/**/*.yaml` files have `expected` fields that are strings containing JSON. I find this hard to read, and it also means the tests have to parse JSON after parsing YAML.

**Describe the solution you'd like**

I'd like the test data to just be YAML. So instad of this:

https://github.com/cucumber/cucumber-expressions/blob/4b6ae11dde0b463b1d4da02def2e4fde7288f79d/testdata/ast/alternation.yaml#L1-L12

```yaml
expression: mice/rats
expected: |-
  {"type": "EXPRESSION_NODE", "start": 0, "end": 9, "nodes": [
    {"type": "ALTERNATION_NODE", "start": 0, "end": 9, "nodes": [
      {"type": "ALTERNATIVE_NODE", "start": 0, "end": 4, "nodes": [
        {"type": "TEXT_NODE", "start": 0, "end": 4, "token": "mice"}
      ]},
      {"type": "ALTERNATIVE_NODE", "start": 5, "end": 9, "nodes": [
        {"type": "TEXT_NODE", "start": 5, "end": 9, "token": "rats"}
      ]}
    ]}
  ]}
```

We'd have this instead:

```yaml
type: EXPRESSION_NODE
start: 0
end: 9
nodes:
- type: ALTERNATION_NODE
  start: 0
  end: 9
  nodes:
  - type: ALTERNATIVE_NODE
    start: 0
    end: 4
    nodes:
    - type: TEXT_NODE
      start: 0
      end: 4
      token: mice
  - type: ALTERNATIVE_NODE
    start: 5
    end: 9
    nodes:
    - type: TEXT_NODE
      start: 5
      end: 9
      token: rats
```

Any objections if I convert the test data? (I'd also change `JSON.parse(expectation.expected)` to just `expectation.expected` in the tests.
